### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by sadiq81** [netbe/Babelish#116]
14: from /Users/tommysadiqhinrichsen/.gem/bin/babelfish:23:in `<main>'
	13: from /Users/tommysadiqhinrichsen/.gem/bin/babelfish:23:in `load'
	12: from /Users/tommysadiqhinrichsen/.gem/gems/babelfish-0.0.1/bin/babelfish:15:in `<top (required)>'
	11: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /Users/tommysadiqhinrichsen/.gem/gems/babelfish-0.0.1/lib/babelfish.rb:10:in `<top (required)>'
	 8: from /Users/tommysadiqhinrichsen/.gem/gems/babelfish-0.0.1/lib/babelfish.rb:39:in `<module:BabelFish>'
	 7: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:31:in `open'
	 6: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	 5: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	 4: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	 3: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	 2: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	 1: from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
/usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 404 Not Found

**Comment by sadiq81** [comment]
Happens every time and on all commands
