### ISSUE TITLE
Cannot load such file -- babelish/keys

### ISSUE THREAD

**Issue by mihbt** [netbe/Babelish#123]
Hello!

After updating to **0.6.2** I'm receiving the following error when running `babelish`:
```
Traceback (most recent call last):
        9: from /Users/mihai.batista/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        8: from /Users/mihai.batista/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        7: from /Users/mihai.batista/.rvm/gems/ruby-2.6.3/bin/babelish:23:in `<main>'
        6: from /Users/mihai.batista/.rvm/gems/ruby-2.6.3/bin/babelish:23:in `load'
        5: from /Users/mihai.batista/.rvm/gems/ruby-2.6.3/gems/babelish-0.6.2/bin/babelish:3:in `<top (required)>'
        4: from /Users/mihai.batista/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /Users/mihai.batista/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /Users/mihai.batista/.rvm/gems/ruby-2.6.3/gems/babelish-0.6.2/lib/babelish.rb:27:in `<top (required)>'
        1: from /Users/mihai.batista/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mihai.batista/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- babelish/keys (LoadError)
```
Any pointers on how to solve this issue are much appreciated.

Best regards,
Mihai

**Comment by borut-t** [comment]
Same here. This is a dealbreaker. @netbe can you take a look at this? Version `0.6.2` makes babelish useless 🤷‍♂

**Comment by NicoDB79** [comment]
Same issue here with version 0.6.2
Any help will be appreciated, thank you.
Nicola.

**Comment by netbe** [comment]
related to #121

**Comment by netbe** [comment]
Hi @NicoDB79. have 0.6.3 a try!

**Comment by NicoDB79** [comment]
Great! Now it works perfectly!
Thank you,
Nicola.
