### ISSUE TITLE
Google docs SSL_connect issue on windows hosts

### ISSUE THREAD

**Issue by borut-t** [netbe/Babelish#85]
Hello,

we are having issues running Babelish when "fetch" property is set to "true".
This is the error we get:

```bash
C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
        from C:/Ruby200-x64/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `connect'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:851:in `start'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1373:in `request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/signet-0.7.2/lib/signet/oauth_2/client.rb:960:in `fetch_access_token'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/signet-0.7.2/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/google_drive-1.0.5/lib/google_drive.rb:154:in `saved_session'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/lib/babelish/google_doc.rb:45:in `authenticate'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/lib/babelish/google_doc.rb:50:in `file_with_name'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/lib/babelish/google_doc.rb:27:in `download_spreadsheet'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/lib/babelish/commandline.rb:116:in `download'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/lib/babelish/commandline.rb:135:in `csv2base'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/lib/babelish/commandline.rb:37:in `block (2 levels) in <class:Commandline>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/babelish-0.4.2/bin/babelish:6:in `<top (required)>'
        from C:/Ruby200-x64/bin/babelish:23:in `load'
        from C:/Ruby200-x64/bin/babelish:23:in `<main>'
```

We've searched for solution with no luck. Could you take a look and suggest what to do?

Thanks!

**Comment by netbe** [comment]
@borut-t  could be related to ruby itself, see https://coderwall.com/p/ouseaa/

**Comment by borut-t** [comment]
@netbe It looks like this solution is Mac only. What about windows?

**Comment by netbe** [comment]
@borut-t no idea, but I guess downloading the cert and figuring out where to put it on windows will make this work

**Comment by borut-t** [comment]
@netbe You are probably right. Thanks!
